<a href="https://colab.research.google.com/github/saivedant09-gif/EXPLORATORY-DATA-ANALYSIS-2026-27/blob/main/Exp5_04_08_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***TASK-1: Discretization and binning***

In [46]:
import pandas as pd
import numpy as np

In [47]:
simple_data = [10, 15, 22, 28, 35, 41, 48, 55, 62, 68, 75, 81, 88, 95]

In [48]:
simple_bins = [0, 25, 50, 75, 100]
simple_labels = ['Low', 'Medium', 'High', 'Very High']
simple_categories_cut = pd.cut(simple_data, bins=simple_bins, labels=simple_labels, include_lowest=True)
display(simple_categories_cut)
display(pd.Series(simple_categories_cut).value_counts())

['Low', 'Low', 'Low', 'Medium', 'Medium', ..., 'High', 'High', 'Very High', 'Very High', 'Very High']
Length: 14
Categories (4, object): ['Low' < 'Medium' < 'High' < 'Very High']

Medium       4
High         4
Low          3
Very High    3
Name: count, dtype: int64

In [49]:
simple_q_labels = ['Bottom 33%', 'Middle 33%', 'Top 33%']
simple_categories_qcut = pd.qcut(simple_data, q=3, labels=simple_q_labels, duplicates='drop')
display(simple_categories_qcut)
display(pd.Series(simple_categories_qcut).value_counts())

['Bottom 33%', 'Bottom 33%', 'Bottom 33%', 'Bottom 33%', 'Bottom 33%', ..., 'Top 33%', 'Top 33%', 'Top 33%', 'Top 33%', 'Top 33%']
Length: 14
Categories (3, object): ['Bottom 33%' < 'Middle 33%' < 'Top 33%']

Bottom 33%    5
Top 33%       5
Middle 33%    4
Name: count, dtype: int64

***TASK-2: Outlier detection and filtering***

In [50]:

df_fraud_test = pd.read_csv('/content/fraudTest.csv')
display(df_fraud_test.head())
display(df_fraud_test.info())

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             555719 non-null  int64
 1   trans_date_trans_time  555719 non-null  object
 2   cc_num                 555719 non-null  int64
 3   merchant               555719 non-null  object
 4   category               555719 non-null  object
 5   amt                    555719 non-null  float64
 6   first                  555719 non-null  object
 7   last                   555719 non-null  object
 8   gender                 555719 non-null  object
 9   street                 555719 non-null  object
 10  city                   555719 non-null  object
 11  state                  555719 non-null  object
 12  zip                    555719 non-null  int64
 13  lat                    555719 non-null  float64
 14  long                   555719 non-null  float64
 15  city_pop               555719 non-null  int64
 16  job                    555719 non-null  object
 17  dob                    555719 non-null  object
 18  trans_num              555719 non-null  object
 19  unix_time              555719 non-null  int64
 20  merch_lat              555719 non-null  float64
 21  merch_long             555719 non-null  float64
 22  is_fraud               555719 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 97.5+ MB

None

In [51]:

Q1_amt = df_fraud_test['amt'].quantile(0.25)
Q3_amt = df_fraud_test['amt'].quantile(0.75)
IQR_amt = Q3_amt - Q1_amt
lower_bound_amt = Q1_amt - 1.5 * IQR_amt
upper_bound_amt = Q3_amt + 1.5 * IQR_amt

print(f"Q1 (amount): {Q1_amt:.2f}")
print(f"Q3 (amount): {Q3_amt:.2f}")
print(f"IQR (amount): {IQR_amt:.2f}")
print(f"Lower Bound (amount): {lower_bound_amt:.2f}")
print(f"Upper Bound (amount): {upper_bound_amt:.2f}")

Q1 (amount): 9.63
Q3 (amount): 83.01
IQR (amount): 73.38
Lower Bound (amount): -100.44
Upper Bound (amount): 193.08

In [52]:

outliers_amt = df_fraud_test[(df_fraud_test['amt'] < lower_bound_amt) | (df_fraud_test['amt'] > upper_bound_amt)]

print(f"Number of outliers detected: {len(outliers_amt)}")
print("Sample of outliers (amount):")
display(outliers_amt[['amt', 'is_fraud']].head())

Number of outliers detected: 27778
Sample of outliers (amount):

         amt  is_fraud
33    210.36         0
100   242.35         0
133   558.03         0
167  1199.45         0
245   236.15         0

In [53]:

df_fraud_test_filtered = df_fraud_test[~((df_fraud_test['amt'] < lower_bound_amt) | (df_fraud_test['amt'] > upper_bound_amt))]

print(f"Original dataset size: {len(df_fraud_test)}")
print(f"Dataset size after filtering outliers: {len(df_fraud_test_filtered)}")
display(df_fraud_test_filtered.head())

Original dataset size: 555719
Dataset size after filtering outliers: 527941

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

***TASK-3: Feature scaling and normalization***

In [58]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
df = pd.read_csv('/content/fraudTrain.csv')

print("Original Data (fraudTrain.csv head):\n", df[['amt']].head(), "\n")

Original Data (fraudTrain.csv head):
       amt
0    4.97
1  107.23
2  220.11
3   45.00
4   41.96

### Min-Max Scaling (Normalization)

In [59]:
min_max_scaler = MinMaxScaler()
df_min_max_amt = pd.DataFrame(
 min_max_scaler.fit_transform(df[['amt']]),
 columns=['amt']
)
print("Min-Max Scaled Data for 'amt' column:\n", df_min_max_amt.head(), "\n")

Min-Max Scaled Data for 'amt' column:
         amt
0  0.000137
1  0.003670
2  0.007569
3  0.001520
4  0.001415

### Z-score Standardization

In [60]:
standard_scaler = StandardScaler()
df_standard_amt = pd.DataFrame(
 standard_scaler.fit_transform(df[['amt']]),
 columns=['amt']
)
print("Standardized Data for 'amt' column:\n", df_standard_amt.head(), "\n")

Standardized Data for 'amt' column:
         amt
0 -0.407826
1  0.230039
2  0.934149
3 -0.158132
4 -0.177094

### Robust Scaling

In [61]:
robust_scaler = RobustScaler()
df_robust_amt = pd.DataFrame(
 robust_scaler.fit_transform(df[['amt']]),
 columns=['amt']
)
print("Robust Scaled Data for 'amt' column:\n", df_robust_amt.head(), "\n")

Robust Scaled Data for 'amt' column:
         amt
0 -0.578990
1  0.812491
2  2.348483
3 -0.034290
4 -0.075657